### ISSUE TITLE
Recognizes a comment in code tags as a header

### ISSUE THREAD

**Issue by qw3ry** [imthenachoman/nGitHubTOC#1]
# Bug description
The markdown
````markdown
# foo
```
# bar
```
````
will yield to the following TOC:
```markdown
- [foo](#foo)
- [bar](#bar)
```

# Expected behaviour:
Ignore `#` inside code tags. The above markdown should yield to the ToC
```markdown
- [foo](#foo)
```

**Comment by imthenachoman** [comment]
Yeah, the current script is pretty slim. Let me add some checks for the above. Thanks!
