### ISSUE TITLE
Adds unnecessary hyphens at end when there's an extra space at the end of the line, which breaks the links

### ISSUE THREAD

**Issue by MaximilianKohler** [imthenachoman/nGitHubTOC#8]
It creates this `[Why Centmin Mod? ](#why-centmin-mod-)` which doesn't work due to the `-` at the end. 

Could it ignore extra spaces at the end?

Thanks for this awesome & easy TOC-creator by the way!

**Comment by imthenachoman** [comment]
> Could it ignore extra spaces at the end?

Possibly. I'm curious how GH handles spaces in headings.

Can you share a code snippet of the markdown code that generated that heading?

**Comment by MaximilianKohler** [comment]
It was this `# Why Centmin Mod? `. I tested in github wikis and github ignores the space at the end - both as part of the link, and also as the visible text. IE: the source would be `# Why Centmin Mod? `. but when you select the text on the published page there is no space at the end.

**Comment by imthenachoman** [comment]
Now try?

**Comment by MaximilianKohler** [comment]
Works great, thanks!
