### ISSUE TITLE
Underscores '_' removed, resulting in invalid links

### ISSUE THREAD

**Issue by Moonbase59** [imthenachoman/nGitHubTOC#9]
When converting my [`autocue` README.md](https://github.com/Moonbase59/autocue/blob/master/README.md), I realized that underscores `_` are removed, resulting in invalid links.

For example, the heading

```
### Install `cue_file`
```

gets converted to

```
  - [Install `cue_file`](#install-cuefile)
```

instead of

```
  - [Install `cue_file`](#install-cue_file)
```

Thanks for a very usable little tool!

**Comment by imthenachoman** [comment]
@orion486 You updated the code in https://github.com/imthenachoman/nGitHubTOC/commit/1d76f3141968a8e496d4bff0631b98458c9b1f50 to replace `_` in the anchor.

I am wondering if some MD parsers don't like `_` and some do?

**Comment by Moonbase59** [comment]
Hi @imthenachoman, thanks for making this and sharing! I made a [fork](https://github.com/Moonbase59/gh-toc) for myself and (hopefully) solved all the Unicode/foreign character/underscore/code block problems. A test file is in [`testing.md`](https://github.com/Moonbase59/gh-toc/blob/master/testing.md?plain=1).

You might want to "steal back" the code in [`gh-toc.js`](https://github.com/Moonbase59/gh-toc/blob/master/gh-toc.js) for yours. :wink:

**Comment by imthenachoman** [comment]
@Moonbase59 Nice. I will play with this in a few weeks. Busy time right now with work.

**Comment by Moonbase59** [comment]
Just to let you know:
- added support for all kinds of code blocks (backticks, tildes, more than 3, uneven stop/start)
- added support for YAML/Jekyll front matter

Let me know if you find bugs :-)

**Comment by orion486** [comment]
> @orion486 You updated the code in [1d76f31](https://github.com/imthenachoman/nGitHubTOC/commit/1d76f3141968a8e496d4bff0631b98458c9b1f50) to replace `_` in the anchor.
> 
> I am wondering if some MD parsers don't like `_` and some do?

I think the cause is that on [line 34](https://github.com/imthenachoman/nGitHubTOC/blob/31180b245d858bc265f27d5de9d217a48195ce3b/nGitHubTOC.js#L34) the regex's handling `*` and `_` are deleting them whether each come in pairs or not in a line. The desired behavior should be to delete these only when they are paired with the same kind, as that indicates they are for formatting. I'll be checking if there is a regex that can do this, otherwise javascript code might be need to handle this.

**Comment by MaximilianKohler** [comment]
This is still happening for me. Eg: `Donor 15, OR_JO_1993` becomes `- [Donor 15, OR_JO_1993](#donor-15-orjo1993)`.

`Donor 5 (2nd try), and #6 & 7:` also becomes `[Donor 5 (2nd try), and #6 & 7:](#donor-5-2nd-try-and-6--7)` instead of `#donor-5-2nd-try-and-6-7`.
